
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.example.practica1.source;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LINEA = 3;
  public static final int SUMA = 8;
  public static final int CURVA = 4;
  public static final int ANIMAR = 5;
  public static final int ERROR = 19;
  public static final int COLOR = 18;
  public static final int PA2 = 13;
  public static final int CUADRADO = 20;
  public static final int PA1 = 12;
  public static final int OBJETO = 6;
  public static final int GRAFICAR = 2;
  public static final int COMA = 14;
  public static final int NUMBER = 21;
  public static final int EOF = 0;
  public static final int MULT = 10;
  public static final int DIV = 11;
  public static final int POLIGONO = 17;
  public static final int error = 1;
  public static final int CIRCULO = 15;
  public static final int ANTERIOR = 7;
  public static final int RECTANGULO = 16;
  public static final int RESTA = 9;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "GRAFICAR",
  "LINEA",
  "CURVA",
  "ANIMAR",
  "OBJETO",
  "ANTERIOR",
  "SUMA",
  "RESTA",
  "MULT",
  "DIV",
  "PA1",
  "PA2",
  "COMA",
  "CIRCULO",
  "RECTANGULO",
  "POLIGONO",
  "COLOR",
  "ERROR",
  "CUADRADO",
  "NUMBER"
  };
}

